version: "3.5"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres:alpine
    container_name: "my_postgres"
    environment:
      POSTGRES_DB: jwt-auth
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - jwt_dbdata:/var/lib/postgresql/data
volumes:
  jwt_dbdata:
